meta_name: "Clara Pécot"
meta_title: "Clara Pécot - Full stack developer"
meta_description: "Je suis développeuse web full stack, avec une préférence pour le front-end. Découvrez mes projets."
# meta_image: "meta-image.png"
